/* Shared fixture runtime. WebMCP remains page-owned; the backend only supplies active policy. */
(() => {
  const API = window.AgentBridgeConfig?.apiBase || document.querySelector('meta[name="agentbridge-api-base"]')?.content || 'http://localhost:3000';
  const kind = document.body.dataset.agentbridgeFixture, controllers = new Map(); let siteId = null, active = {}, pendingConfirmation = null;
  const definitions = {
    get_menu: { title: 'Get menu', readOnlyHint: true, schema: {}, run: config => ({ items: config.items || [] }) },
    get_opening_hours: { title: 'Get opening hours', readOnlyHint: true, schema: {}, run: config => ({ hours: config.hours || {} }) },
    get_services: { title: 'Get services', readOnlyHint: true, schema: {}, run: config => ({ services: config.services || [] }) },
    request_quote: { title: 'Request quote', readOnlyHint: false, schema: { service: { type: 'string' }, name: { type: 'string' }, email: { type: 'string' }, message: { type: 'string' } }, run: (config, input) => requestConfirmation(config, input) }
  };
  const request = async (path, options = {}) => { const response = await fetch(API + path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error('Policy request failed.'); return response.json(); };
  const supported = () => Boolean(document.modelContext?.registerTool);
  const log = (tool, result, summary) => { if (siteId) request('/api/runtime/activity', { method: 'POST', body: JSON.stringify({ websiteId: siteId, currentUrl: location.href, tool, result, summary: summary || kind + ' fixture adapter execution.' }) }).catch(() => {}); };
  function requestConfirmation(config, input) { return new Promise((resolve, reject) => { pendingConfirmation = { resolve, reject, config, input }; log('request_quote', 'CONFIRMATION_REQUIRED', 'Customer confirmation requested for local quote.'); const panel = document.querySelector('#agentbridge-confirmation'); panel.hidden = false; document.querySelector('#confirmation-summary').textContent = 'AI wants to request a quote for ' + (input.service || 'a service') + (input.name ? ' for ' + input.name : '') + '.'; }); }
  function bindConfirmation() { const panel = document.querySelector('#agentbridge-confirmation'); if (!panel) return; panel.querySelector('[data-confirm]').addEventListener('click', () => { if (!pendingConfirmation) return; const { resolve, input } = pendingConfirmation; pendingConfirmation = null; panel.hidden = true; document.querySelector('#agentbridge-result').textContent = 'Quote request confirmed and recorded locally.'; log('request_quote', 'SUCCESS', 'Local quote request confirmed.'); resolve({ confirmed: true, action: 'request_quote', summary: 'Local quote request recorded.', confirmationMessage: 'Customer confirmed this local fixture request.', request: { service: input.service || '', name: input.name || '' } }); }); panel.querySelector('[data-cancel]').addEventListener('click', () => { if (!pendingConfirmation) return; const { reject } = pendingConfirmation; pendingConfirmation = null; panel.hidden = true; document.querySelector('#agentbridge-result').textContent = 'Quote request cancelled.'; log('request_quote', 'CANCELLED', 'Customer cancelled local quote request.'); reject(new Error('Customer cancelled the quote request.')); }); }
  async function reconcile() { const names = Object.keys(active).filter(name => definitions[name]); [...controllers.keys()].filter(name => !names.includes(name)).forEach(name => { controllers.get(name).abort(); controllers.delete(name); }); if (!supported()) return; for (const name of names) { if (controllers.has(name)) continue; const definition = definitions[name], controller = new AbortController(); await document.modelContext.registerTool({ name, title: definition.title, description: definition.readOnlyHint ? 'Read merchant-configured AgentBridge fixture data.' : 'Prepare a local quote request and show a customer confirmation step.', inputSchema: { type: 'object', properties: definition.schema }, annotations: { readOnlyHint: definition.readOnlyHint, requiresConfirmation: Boolean(active[name].requiresConfirmation) }, execute: async input => { try { const value = await definition.run(active[name].config || {}, input || {}); if (name !== 'request_quote') log(name, 'SUCCESS'); return value; } catch (error) { if (name !== 'request_quote') log(name, 'ERROR'); throw error; } } }, { signal: controller.signal }); controllers.set(name, controller); } }
  async function refresh() { try { const response = await request('/api/runtime/policy?url=' + encodeURIComponent(location.href)); siteId = response.website?.id || null; active = response.policy?.tools || {}; await reconcile(); renderDebug(); } catch { active = {}; await reconcile(); renderDebug('Backend unavailable'); } }
  function renderDebug(error) { const panel = document.querySelector('#agentbridge-debug'); if (!panel) return; panel.querySelector('[data-runtime]').textContent = error || (supported() ? (controllers.size ? 'SUPPORTED · ACTIVE' : 'SUPPORTED · INACTIVE') : 'UNSUPPORTED'); panel.querySelector('[data-tools]').textContent = controllers.size ? [...controllers.keys()].join(', ') : 'No registered tools'; }
  document.addEventListener('agentbridge:extension-request', event => { if (event.detail?.type === 'runtime-status') document.dispatchEvent(new CustomEvent('agentbridge:runtime-status', { detail: { status: supported() ? (controllers.size ? 'ACTIVE' : 'INACTIVE') : 'UNSUPPORTED', tools: [...controllers.keys()] } })); if (event.detail?.type === 'policy-updated') refresh(); });
  bindConfirmation(); refresh(); setInterval(refresh, 5000);
})();
