/* The website runtime reconciles backend policy with real WebMCP registration. */
(() => {
  const API = window.AgentBridgeConfig?.apiBase || document.querySelector('meta[name="agentbridge-api-base"]')?.content || 'http://localhost:3000';
  const names = ['search_products', 'get_product', 'check_inventory', 'add_to_cart'];
  const labels = { search_products: 'Search products', get_product: 'Product details', check_inventory: 'Check inventory', add_to_cart: 'Add to cart' };
  const state = { agentAccessEnabled: true, toolPermissions: { search_products: true, get_product: true, check_inventory: true, add_to_cart: false } };
  const activity = []; let siteId = null, connected = false, lifecycle = Promise.resolve();
  const desired = () => state.agentAccessEnabled ? names.filter(name => state.toolPermissions[name]) : [];
  const emit = () => window.dispatchEvent(new CustomEvent('agentbridge:statechange'));
  async function request(path, options = {}) { const response = await fetch(API + path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error('Policy request failed.'); return response.json(); }
  function reconcile() { lifecycle = lifecycle.then(async () => { const runtime = window.AgentBridgeWebMCP, wanted = desired(), existing = runtime.getRegisteredToolNames(); runtime.unregisterTools(existing.filter(name => !wanted.includes(name))); await runtime.registerTools(wanted.filter(name => !existing.includes(name))); emit(); }); return lifecycle; }
  async function refreshPolicy() { try { const result = await request('/api/runtime/policy?url=' + encodeURIComponent(location.href)); connected = Boolean(result.connected); if (connected) { siteId = result.website.id; state.agentAccessEnabled = result.policy.agentAccessEnabled; names.forEach(name => { state.toolPermissions[name] = Boolean(result.policy.tools[name]?.enabled); }); } await reconcile(); render(); } catch { connected = false; await reconcile(); render(); } }
  async function setAccess(enabled) { if (!connected) { state.agentAccessEnabled = enabled; return reconcile(); } await request('/api/extension/sites/' + siteId + '/access', { method: 'PATCH', body: JSON.stringify({ currentUrl: location.href, agentAccessEnabled: enabled }) }); return refreshPolicy(); }
  async function setToolPermission(name, enabled) { if (!connected) { state.toolPermissions[name] = enabled; return reconcile(); } await request('/api/extension/sites/' + siteId + '/tools/' + encodeURIComponent(name), { method: 'PATCH', body: JSON.stringify({ currentUrl: location.href, enabled }) }); return refreshPolicy(); }
  function recordActivity(toolName, argumentsObject, resultStatus) { activity.unshift({ timestamp: new Date(), toolName, argumentsObject, resultStatus }); activity.splice(12); if (connected && siteId) request('/api/runtime/activity', { method: 'POST', body: JSON.stringify({ websiteId: siteId, currentUrl: location.href, tool: toolName, result: resultStatus, summary: 'Demo-store tool executed.' }) }).catch(() => {}); emit(); }
  function confirmAction(details, action) { return new Promise((resolve, reject) => { const panel = document.querySelector('#agentbridge-confirmation'); recordActivity(details.action, {}, 'CONFIRMATION_REQUIRED'); document.querySelector('#confirmation-summary').textContent = details.summary; panel.hidden = false; const finish = async confirmed => { panel.hidden = true; if (!confirmed) return reject(new Error('Customer cancelled this action.')); try { const result = await action(); resolve({ ...result, confirmation: { requiresConfirmation: true, action: details.action, summary: details.summary, confirmationMessage: details.confirmationMessage, confirmed: true } }); } catch (error) { reject(error); } }; panel.querySelector('[data-confirm]').onclick = () => finish(true); panel.querySelector('[data-cancel]').onclick = () => finish(false); }); }
  window.AgentBridge = { state, activity, enableAgentAccess: () => setAccess(true), disableAgentAccess: () => setAccess(false), registerApprovedTools: reconcile, unregisterAllTools: () => { window.AgentBridgeWebMCP.unregisterAllTools(); emit(); }, setToolPermission, recordActivity, confirmAction, getRegisteredTools: () => window.AgentBridgeWebMCP.getRegisteredToolNames(), isWebMCPSupported: () => window.AgentBridgeWebMCP.supported(), refreshPolicy };
  const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const args = input => Object.entries(input).map(([key, value]) => esc(key) + '=' + esc(typeof value === 'string' ? '"' + value + '"' : value)).join(', ');
  function render() {
    const registered = window.AgentBridge.getRegisteredTools(), supported = window.AgentBridge.isWebMCPSupported();
    document.querySelector('#master-switch').checked = state.agentAccessEnabled;
    document.querySelector('#master-state').textContent = state.agentAccessEnabled ? 'ON — AGENT ACCESS ENABLED' : 'OFF — AGENT ACCESS PAUSED';
    document.querySelector('#bridge-console').classList.toggle('is-off', !state.agentAccessEnabled);
    document.querySelector('#webmcp-status').textContent = supported ? (registered.length ? 'WebMCP: ACTIVE' : 'WebMCP: INACTIVE') : 'WebMCP: UNSUPPORTED';
    document.querySelector('#tool-list').innerHTML = registered.length ? registered.map(name => '<li>' + name + '</li>').join('') : '<li>None exposed</li>';
    const row = name => '<label class="permission-row ' + (state.toolPermissions[name] ? 'allowed' : 'denied') + '"><span><b>' + labels[name] + '</b><small>' + (name === 'add_to_cart' ? 'ACTION' : 'READ') + '</small></span><input type="checkbox" data-permission="' + name + '" ' + (state.toolPermissions[name] ? 'checked' : '') + '><i></i><em>' + (state.toolPermissions[name] ? 'ALLOWED' : 'DENIED') + '</em></label>';
    document.querySelector('#permission-list').innerHTML = '<p class="permission-group">READ</p>' + names.slice(0, 3).map(row).join('') + '<p class="permission-group">ACTION</p>' + row('add_to_cart');
    document.querySelector('#tool-status-list').innerHTML = names.map(name => '<li><div><b>' + name + '</b><small>Permission: <span class="' + (state.toolPermissions[name] ? 'good' : 'bad') + '">' + (state.toolPermissions[name] ? 'ALLOWED' : 'DENIED') + '</span></small></div><span class="status-chip ' + (registered.includes(name) ? 'registered' : 'hidden') + '">' + (registered.includes(name) ? 'REGISTERED' : 'NOT EXPOSED') + '</span></li>').join('');
    document.querySelector('#agent-tools').innerHTML = registered.length ? registered.map(name => '<li>✓ ' + name + '</li>').join('') : '<li class="none">No tools are currently exposed.</li>';
    document.querySelector('#activity-log').innerHTML = activity.length ? activity.map(entry => '<li><time>' + entry.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) + '</time><b>' + entry.toolName + '</b><span>' + args(entry.argumentsObject) + '</span><em class="' + (entry.resultStatus === 'SUCCESS' ? 'good' : 'bad') + '">' + entry.resultStatus + '</em></li>').join('') : '<li class="none">Awaiting agent activity.</li>';
  }
  document.querySelector('#master-switch').addEventListener('change', event => setAccess(event.target.checked));
  document.querySelector('#permission-list').addEventListener('change', event => { if (event.target.matches('[data-permission]')) setToolPermission(event.target.dataset.permission, event.target.checked); });
  window.addEventListener('agentbridge:statechange', render); window.addEventListener('agentbridge:webmcpchange', render);
  document.addEventListener('agentbridge:extension-request', event => { if (event.detail?.type === 'runtime-status') document.dispatchEvent(new CustomEvent('agentbridge:runtime-status', { detail: { status: window.AgentBridgeWebMCP.supported() ? (window.AgentBridgeWebMCP.getRegisteredToolNames().length ? 'ACTIVE' : 'INACTIVE') : 'UNSUPPORTED', tools: window.AgentBridgeWebMCP.getRegisteredToolNames() } })); if (event.detail?.type === 'policy-updated') refreshPolicy(); });
  render(); refreshPolicy(); setInterval(refreshPolicy, 5000);
})();
