/* Shared storefront state. Both the human UI and WebMCP tools use this object. */
(() => {
  const products = [
    { id: 'black-running-shoes', name: 'Black Running Shoes', category: 'footwear', price: 79, inventory: 12, visual: 'shoe-one', description: 'A lightweight everyday runner with a cushioned stride and grippy rubber sole.' },
    { id: 'performance-runner', name: 'Performance Runner', category: 'footwear', price: 89, inventory: 7, visual: 'shoe-two', description: 'Responsive foam and a breathable upper for your fastest training days.' },
    { id: 'black-formal-shirt', name: 'Black Formal Shirt', category: 'apparel', price: 55, inventory: 18, visual: 'shirt', description: 'A crisp, tailored shirt cut from comfortable stretch cotton.' },
    { id: 'travel-backpack', name: 'Travel Backpack', category: 'accessories', price: 65, inventory: 9, visual: 'backpack', description: 'A compact 24L carry-all with a padded laptop sleeve and easy-access pockets.' }
  ];
  const cart = [];
  const money = value => `$${value.toFixed(2)}`;
  const productFor = id => products.find(product => product.id === id);
  const cartCount = () => cart.reduce((total, item) => total + item.quantity, 0);
  const cartTotal = () => cart.reduce((total, item) => total + productFor(item.productId).price * item.quantity, 0);
  const findProducts = (query = '', category = 'all') => { const terms = String(query).toLowerCase().trim().split(/\s+/).filter(Boolean); return products.filter(product => (category === 'all' || product.category === category) && terms.every(term => `${product.name} ${product.category} ${product.description}`.toLowerCase().includes(term))); };
  const productSummary = product => ({ id: product.id, name: product.name, category: product.category, price: product.price, currency: 'USD', inStock: product.inventory > 0, inventory: product.inventory, description: product.description });

  const grid = document.querySelector('#product-grid'), empty = document.querySelector('#empty-state'), search = document.querySelector('#search-input');
  let selectedFilter = 'all';
  function visual(product, details = false) { return `<div class="product-visual ${details ? 'details-visual' : ''}"><div class="shape ${product.visual}"></div></div>`; }
  function renderProducts() { const matches = findProducts(search.value, selectedFilter); empty.hidden = matches.length > 0; grid.innerHTML = matches.map(product => `<article class="product-card">${visual(product)}<div class="product-info"><div><h3>${product.name}</h3><small>${product.inventory} in stock</small></div><p>${money(product.price)}</p></div><div class="card-actions"><button data-details="${product.id}">Details</button><button data-add="${product.id}">Add to bag</button></div></article>`).join(''); }
  function renderCart() { const items = cart.map(item => ({ ...item, product: productFor(item.productId) })); document.querySelector('#cart-count').textContent = cartCount(); document.querySelector('#cart-total').textContent = money(cartTotal()); document.querySelector('#cart-items').innerHTML = items.length ? items.map(({ product, quantity }) => `<div class="cart-item"><div><h3>${product.name}</h3><p>${money(product.price)} each</p><div class="quantity-controls"><button data-cart-change="${product.id}" data-delta="-1" aria-label="Remove one ${product.name}">−</button><span>${quantity}</span><button data-cart-change="${product.id}" data-delta="1" aria-label="Add one ${product.name}">+</button></div></div><strong>${money(product.price * quantity)}</strong></div>`).join('') : '<p class="empty-state">Your bag is waiting for something good.</p>'; }
  let toastTimer; function toast(message) { const node = document.querySelector('#toast'); node.textContent = message; node.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => node.classList.remove('show'), 2600); }
  function addToCart(productId, quantity = 1) { const product = productFor(productId), amount = Number(quantity); if (!product) return { ok: false, message: 'Product not found.' }; if (!Number.isInteger(amount) || amount < 1) return { ok: false, message: 'Quantity must be a positive whole number.' }; const existing = cart.find(item => item.productId === productId); const current = existing?.quantity || 0; if (current + amount > product.inventory) return { ok: false, message: `Only ${product.inventory} ${product.name} available.` }; if (existing) existing.quantity += amount; else cart.push({ productId, quantity: amount }); renderCart(); toast(`${product.name} added to your bag.`); return { ok: true, cart: getCart() }; }
  function getCart() { return { items: cart.map(item => ({ ...productSummary(productFor(item.productId)), quantity: item.quantity, lineTotal: productFor(item.productId).price * item.quantity })), itemCount: cartCount(), total: cartTotal(), currency: 'USD' }; }
  function showDetails(id) { const product = productFor(id); if (!product) return; document.querySelector('#product-details').innerHTML = `<div class="details">${visual(product, true)}<div class="details-copy"><p class="eyebrow">${product.category}</p><h2>${product.name}</h2><strong>${money(product.price)}</strong><p>${product.description}</p><p><b>${product.inventory} available now</b></p><button class="button button-dark" data-add="${product.id}">Add to bag <span>→</span></button></div></div>`; document.querySelector('#product-dialog').showModal(); }
  function toggleCart(open) { document.querySelector('#cart-drawer').classList.toggle('open', open); document.querySelector('#scrim').classList.toggle('show', open); document.querySelector('#cart-button').setAttribute('aria-expanded', open); document.querySelector('#cart-drawer').setAttribute('aria-hidden', !open); }
  document.addEventListener('click', event => { const add = event.target.closest('[data-add]'); const details = event.target.closest('[data-details]'); const change = event.target.closest('[data-cart-change]'); if (add) { addToCart(add.dataset.add); } if (details) showDetails(details.dataset.details); if (change) { const item = cart.find(entry => entry.productId === change.dataset.cartChange); const delta = Number(change.dataset.delta); if (delta === -1 && item) { item.quantity === 1 ? cart.splice(cart.indexOf(item), 1) : item.quantity -= 1; } else if (delta === 1) addToCart(change.dataset.cartChange, 1); renderCart(); } });
  search.addEventListener('input', renderProducts); document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { selectedFilter = button.dataset.filter; document.querySelectorAll('.filter').forEach(node => node.classList.toggle('active', node === button)); renderProducts(); }));
  document.querySelector('#cart-button').addEventListener('click', () => toggleCart(true)); document.querySelector('#close-cart').addEventListener('click', () => toggleCart(false)); document.querySelector('#scrim').addEventListener('click', () => toggleCart(false)); document.querySelector('#close-dialog').addEventListener('click', () => document.querySelector('#product-dialog').close()); document.querySelector('#checkout-button').addEventListener('click', () => toast('Demo checkout only — no payment is collected.'));
  window.AgentBridgeStorefront = { products, searchProducts: findProducts, getProduct: id => productFor(id), getProductSummary: productSummary, addToCart, getCart, toast };
  renderProducts(); renderCart();
})();
