const assert = require('assert');
const registry = require('../services/adapters/registry');
const menu = { id: 'menu', suggestedToolName: 'get_menu', name: 'View menu' };
const quote = { id: 'quote', suggestedToolName: 'request_quote', name: 'Request quote' };
const demo = { id: 'demo', suggestedToolName: 'search_products', name: 'Search products' };
const base = { verified: true, agentAccessEnabled: true, capabilities: [menu, quote, demo], tools: { get_menu: { enabled: true }, request_quote: { enabled: true }, search_products: { enabled: true } }, adapters: {} };
assert.equal(registry.status(base, menu).status, 'configuration_required');
assert.equal(registry.status(base, demo).status, 'configured');
assert.deepEqual(Object.keys(registry.activeTools(base)), ['search_products']);
const configured = { ...base, adapters: { menu: { adapterId: 'static-data', config: { items: ['Soup', 'Salad'] } }, quote: { adapterId: 'form-action', config: { fields: ['name', 'email', 'message'] } } } };
const active = registry.activeTools(configured);
assert.equal(active.get_menu.status, 'active');
assert.equal(active.request_quote.requiresConfirmation, true);
assert.equal(registry.get('form-action').validate({ fields: [] }), false);
assert.equal(registry.get('static-data').validate({ items: ['Soup'] }), true);
assert.equal(registry.get('missing-adapter'), undefined);
assert.deepEqual(Object.keys(registry.activeTools({ ...configured, agentAccessEnabled: false })), []);
assert.equal(registry.get('form-action').execute({ tool: 'request_quote', config: { fields: ['email'] } }).confirmationRequired, true);
console.log('Adapter registry tests passed: activation gates, validation, confirmation, and disabled policy.');
