const config = require('../config');
const { inspectHtml, genericCapabilities } = require('./analyzers/generic');
const { ecommerceCapabilities } = require('./analyzers/ecommerce');
const { restaurantCapabilities } = require('./analyzers/restaurant');
const { serviceCapabilities } = require('./analyzers/services');
const MAX_HTML_BYTES = 1024 * 1024, TIMEOUT_MS = 7000;
function safeUrl(value) { let url; try { url = new URL(value); } catch { throw new Error('Enter a valid http(s) website URL.'); } if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) throw new Error('Only plain http(s) website URLs are supported.'); const host = url.hostname.toLowerCase(), octets = host.split('.').map(Number), privateIpv4 = octets.length === 4 && (octets[0] === 10 || octets[0] === 0 || octets[0] === 169 && octets[1] === 254 || octets[0] === 172 && octets[1] >= 16 && octets[1] <= 31 || octets[0] === 192 && octets[1] === 168); if ((privateIpv4 && host !== '127.0.0.1') || ['0.0.0.0', '::', '[::]'].includes(host) || /^\[?(?:fc|fd|fe80):/i.test(host)) throw new Error('This host is not supported.'); return url; }
async function fetchHtml(value) { const start = safeUrl(value), controller = new AbortController(), timeout = setTimeout(() => controller.abort(), TIMEOUT_MS); try { const response = await fetch(start, { signal: controller.signal, redirect: 'follow', headers: { 'User-Agent': 'AgentBridge-Capability-Analyzer/1.0', Accept: 'text/html,application/xhtml+xml' } }), finalUrl = safeUrl(response.url); if (!response.ok) throw new Error('The website did not return a successful response.'); if (Number(response.headers.get('content-length') || 0) > MAX_HTML_BYTES) throw new Error('The website response is too large to analyze.'); const reader = response.body?.getReader(); let size = 0, chunks = []; if (!reader) return { html: '', finalUrl }; while (true) { const { done, value: chunk } = await reader.read(); if (done) break; size += chunk.length; if (size > MAX_HTML_BYTES) { await reader.cancel(); throw new Error('The website response is too large to analyze.'); } chunks.push(chunk); } return { html: Buffer.concat(chunks).toString('utf8'), finalUrl }; } finally { clearTimeout(timeout); } }
function isHostedDemo(url) {
  if (!config.publicBaseUrl) return false;
  const base = new URL(config.publicBaseUrl);
  return url.origin === base.origin && ['/store', '/store/', '/store/index.html'].includes(url.pathname);
}
async function analyzeWebsite(url) { const { html, finalUrl } = await fetchHtml(url), signals = inspectHtml(html), context = { url: finalUrl, signals, isKnownDemo: isHostedDemo(finalUrl) || ((finalUrl.hostname === 'localhost' || finalUrl.hostname === '127.0.0.1') && (finalUrl.port === '8080' || finalUrl.port === '3000' && finalUrl.pathname.startsWith('/store'))) || finalUrl.hostname.includes('demo-store') }, capabilities = [...ecommerceCapabilities(context), ...restaurantCapabilities(context), ...serviceCapabilities(context), ...genericCapabilities(context)], unique = new Map(); capabilities.forEach(capability => { const prior = unique.get(capability.suggestedToolName); if (!prior || prior.confidence < capability.confidence) unique.set(capability.suggestedToolName, capability); }); return { analyzedUrl: finalUrl.toString(), adapter: context.isKnownDemo ? 'known-agentbridge-demo-store' : 'html-signals-only', signals: { title: signals.title, schemas: signals.schemas, headingCount: signals.headings.length, links: signals.links.length, forms: signals.forms.length }, capabilities: [...unique.values()].sort((a, b) => b.confidence - a.confidence), message: 'Capabilities are deterministic HTML signals only. Detection does not execute website actions.' }; }
module.exports = { analyzeWebsite, fetchHtml };
